-- ============================================================
--  MuYang 쇼핑몰 스키마 (PostgreSQL)
--  DBeaver에서 muyang 데이터베이스에 연결 후 이 스크립트를 실행하세요.
--  컬럼/타입/IDENTITY는 JPA 엔티티(ddl-auto=validate)와 일치하도록 맞췄습니다.
-- ============================================================

-- ── 초기화 (재실행 시 깨끗하게) ──────────────────────────────
DROP TABLE IF EXISTS user_coupons     CASCADE;
DROP TABLE IF EXISTS coupons          CASCADE;
DROP TABLE IF EXISTS point_transactions CASCADE;
DROP TABLE IF EXISTS reviews          CASCADE;
DROP TABLE IF EXISTS addresses        CASCADE;
DROP TABLE IF EXISTS payments         CASCADE;
DROP TABLE IF EXISTS order_items      CASCADE;
DROP TABLE IF EXISTS orders           CASCADE;
DROP TABLE IF EXISTS wishlist_items   CASCADE;
DROP TABLE IF EXISTS wishlists        CASCADE;
DROP TABLE IF EXISTS cart_items       CASCADE;
DROP TABLE IF EXISTS carts            CASCADE;
DROP TABLE IF EXISTS sku_attributes   CASCADE;
DROP TABLE IF EXISTS sku_images       CASCADE;
DROP TABLE IF EXISTS skus             CASCADE;
DROP TABLE IF EXISTS sku_details      CASCADE;
DROP TABLE IF EXISTS pets             CASCADE;
DROP TABLE IF EXISTS promos           CASCADE;
DROP TABLE IF EXISTS categories       CASCADE;
DROP TABLE IF EXISTS users            CASCADE;

-- ── 회원 ─────────────────────────────────────────────────────
CREATE TABLE users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            VARCHAR(255) UNIQUE,
    password         VARCHAR(255),
    name             VARCHAR(255),
    role             VARCHAR(255),               -- USER / ADMIN
    grade            VARCHAR(255),               -- BRONZE / SILVER / GOLD / VIP
    onboarded        BOOLEAN      NOT NULL DEFAULT FALSE,
    marketing_agreed BOOLEAN      NOT NULL DEFAULT FALSE,
    agreed_at        TIMESTAMPTZ,
    created_at       TIMESTAMPTZ,
    provider         VARCHAR(255),               -- LOCAL / KAKAO / NAVER (소셜 로그인)
    provider_id      VARCHAR(255)                -- 소셜 고유 ID (LOCAL이면 NULL)
);
COMMENT ON TABLE users IS '회원 계정';

-- ── 카탈로그 ─────────────────────────────────────────────────
CREATE TABLE categories (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cat_key VARCHAR(255),
    label   VARCHAR(255)
);

CREATE TABLE promos (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    big   VARCHAR(255),
    sub   VARCHAR(255),
    theme VARCHAR(255)
);

CREATE TABLE sku_details (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description       VARCHAR(4000),
    extra_description VARCHAR(2000),
    video_url         VARCHAR(255)
);

-- 상품(SKU) — PK가 문자열(p1, p2 …)
CREATE TABLE skus (
    id         VARCHAR(255) PRIMARY KEY,
    name       VARCHAR(255),
    cat        VARCHAR(255),
    pet        VARCHAR(255),
    price      INTEGER      NOT NULL,
    was        INTEGER,                          -- 정가(할인 전), 없으면 NULL
    tag        VARCHAR(255),
    rating     DOUBLE PRECISION NOT NULL,
    reviews    INTEGER      NOT NULL,
    ph         VARCHAR(255),
    summary    VARCHAR(500),                     -- 엔티티 필드명 desc
    sort_order INTEGER      NOT NULL,
    detail_id  BIGINT REFERENCES sku_details(id) ON DELETE SET NULL
);
COMMENT ON TABLE skus IS '판매 상품(SKU)';

CREATE TABLE sku_images (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id     VARCHAR(255) REFERENCES skus(id) ON DELETE CASCADE,
    url        VARCHAR(500),
    type       VARCHAR(255) CHECK (type IN ('MAIN','GALLERY','DETAIL')),
    sort_order INTEGER      NOT NULL,
    alt        VARCHAR(255)
);

CREATE TABLE sku_attributes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id     VARCHAR(255) REFERENCES skus(id) ON DELETE CASCADE,
    name       VARCHAR(255),
    attr_value VARCHAR(255),                     -- 엔티티 필드명 value (value는 예약어라 컬럼명 변경)
    sort_order INTEGER      NOT NULL
);

-- ── 장바구니 (집계 루트 + 항목) ──────────────────────────────
CREATE TABLE carts (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT REFERENCES carts(id) ON DELETE CASCADE,
    product_id VARCHAR(255) REFERENCES skus(id),
    qty        INTEGER      NOT NULL
);

-- ── 위시리스트 ───────────────────────────────────────────────
CREATE TABLE wishlists (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE wishlist_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wishlist_id BIGINT REFERENCES wishlists(id) ON DELETE CASCADE,
    product_id  VARCHAR(255) REFERENCES skus(id)
);

-- ── 주문 ─────────────────────────────────────────────────────
CREATE TABLE orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT REFERENCES users(id),
    subtotal   INTEGER      NOT NULL,
    shipping   INTEGER      NOT NULL,
    total      INTEGER      NOT NULL,
    status     VARCHAR(255),                     -- PENDING / PAID / CANCELED
    created_at TIMESTAMPTZ
);

CREATE TABLE order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id VARCHAR(255) REFERENCES skus(id),
    qty        INTEGER      NOT NULL
);

-- ── 결제 ─────────────────────────────────────────────────────
CREATE TABLE payments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT REFERENCES orders(id),
    user_id     BIGINT REFERENCES users(id),
    provider    VARCHAR(255) CHECK (provider IN ('TOSS','KAKAO','NAVER')),
    status      VARCHAR(255) CHECK (status IN ('READY','PAID','FAILED','CANCELED')),
    amount      INTEGER      NOT NULL,
    pg_key      VARCHAR(255),
    fail_reason VARCHAR(500),
    created_at  TIMESTAMPTZ,
    approved_at TIMESTAMPTZ
);

-- ── 배송지 ───────────────────────────────────────────────────
CREATE TABLE addresses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT REFERENCES users(id) ON DELETE CASCADE,
    label      VARCHAR(255),
    recipient  VARCHAR(255),
    phone      VARCHAR(255),
    zipcode    VARCHAR(255),
    address1   VARCHAR(255),
    address2   VARCHAR(255),
    is_default BOOLEAN      NOT NULL DEFAULT FALSE
);

-- ── 리뷰 (시드 리뷰는 user_id/sku_id 가 NULL일 수 있음) ───────
CREATE TABLE reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id     VARCHAR(255) REFERENCES skus(id) ON DELETE CASCADE,
    user_id    BIGINT REFERENCES users(id) ON DELETE SET NULL,
    name       VARCHAR(255),
    pet        VARCHAR(255),
    rating     INTEGER      NOT NULL,
    content    VARCHAR(500),                     -- 엔티티 필드명 text
    created_at TIMESTAMPTZ
);

-- ── 적립금 (잔액은 거래 합계로 계산) ─────────────────────────
CREATE TABLE point_transactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT REFERENCES users(id) ON DELETE CASCADE,
    amount     INTEGER      NOT NULL,            -- +적립 / -사용
    reason     VARCHAR(255),
    created_at TIMESTAMPTZ
);

-- ── 쿠폰 ─────────────────────────────────────────────────────
CREATE TABLE coupons (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(255) UNIQUE,
    name           VARCHAR(255),
    discount_type  VARCHAR(255) CHECK (discount_type IN ('RATE','AMOUNT')),
    discount_value INTEGER      NOT NULL,
    min_order      INTEGER      NOT NULL,
    active         BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE user_coupons (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT REFERENCES users(id) ON DELETE CASCADE,
    coupon_id BIGINT REFERENCES coupons(id) ON DELETE CASCADE,
    used      BOOLEAN      NOT NULL DEFAULT FALSE,
    issued_at TIMESTAMPTZ,
    used_at   TIMESTAMPTZ
);

-- ── 반려동물 ─────────────────────────────────────────────────
CREATE TABLE pets (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name    VARCHAR(255),
    species VARCHAR(255),
    age     INTEGER                              -- 나이 미입력 가능
);

-- ── 인덱스 (조회 성능 — FK·조회 컬럼) ────────────────────────
CREATE INDEX idx_sku_images_sku        ON sku_images(sku_id);
CREATE INDEX idx_sku_attributes_sku    ON sku_attributes(sku_id);
CREATE INDEX idx_cart_user             ON carts(user_id);
CREATE INDEX idx_cart_items_cart       ON cart_items(cart_id);
CREATE INDEX idx_wishlist_user         ON wishlists(user_id);
CREATE INDEX idx_wishlist_items_wl     ON wishlist_items(wishlist_id);
CREATE INDEX idx_orders_user           ON orders(user_id);
CREATE INDEX idx_order_items_order     ON order_items(order_id);
CREATE INDEX idx_payments_order        ON payments(order_id);
CREATE INDEX idx_payments_user         ON payments(user_id);
CREATE INDEX idx_addresses_user        ON addresses(user_id);
CREATE INDEX idx_reviews_sku           ON reviews(sku_id);
CREATE INDEX idx_reviews_user          ON reviews(user_id);
CREATE INDEX idx_point_tx_user         ON point_transactions(user_id);
CREATE INDEX idx_user_coupons_user     ON user_coupons(user_id);
CREATE INDEX idx_pets_user             ON pets(user_id);

ALTER TABLE skus ADD COLUMN image_url VARCHAR(500);
ALTER TABLE promos ADD COLUMN image_url VARCHAR(500);